version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "github-actions"
    labels:
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:30"
      timezone: "Europe/London"
    commit-message:
      prefix: "npm"
    labels:
      - "dependencies"
