name: documentation

on:
  pull_request:
    branches: [main]
    paths: ['./']
  push:
    branches: [main]
    paths: ['./']
  workflow_dispatch:

jobs:
  pull-request-check:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5.0.0

      - uses: actions/setup-node@v5.0.0
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: "./package-lock.json"

      - name: Test Build
        working-directory: ./
        run: |
          npm ci
          npm run build

  build-docs:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0

      - uses: actions/setup-node@v5.0.0
        with:
          node-version: 22

      - name: Build eleventy
        working-directory: ./
        run: |
          npm ci --ignore-scripts
          npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./_site

  deploy-docs:
    needs: build-docs
    runs-on: ubuntu-latest
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
